### ISSUE TITLE
City names are out of date

### ISSUE THREAD

**Issue by Airswoop1** [sjlu/cities#4]
The city for zip code 11101 is Long Island City. It is incorrectly entered as Astoria.

**Comment by thomaswmanion** [comment]
How do you go about updating the data?

**Comment by sjlu** [comment]
I have to do this manually by pinging USPS

**Comment by thomaswmanion** [comment]
Oh I see. It could be made a bit more efficient by making more than 1 lat/long spot for each zip code. Working on a script right now that would do this.

**Comment by sjlu** [comment]
@thomaswmanion it would, but that'll only be optimal for lat,lng lookups

**Comment by sjlu** [comment]
See e2af4f0
