### ISSUE TITLE
How to Add City

### ISSUE THREAD

**Issue by willSonic** [sjlu/cities#8]
Entering the zip 94501, returns Coast Guard Isla instead of Alameda. Coast Guard Isla is not a California City, County, it is small harbor and dock for the US Coast Guard. Is there a way to add Cities to Zip Codes?

**Comment by sjlu** [comment]
You'd have to edit the raw .json file. I currently do not have a way to auto-update these. Does the postal service return the proper city for you?

**Comment by willSonic** [comment]
Hi Steven,

I actually forked it and updated the location.json  in my version. When I
put in the zipcode 94501, it returned with Coast Guard Isle, which is a
small I island of the coast of Alameda. The correct City for the postal
code 94501, is Alameda. This is what is returned when you go the USPS,
 https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=2&companyName=&address1=&address2=&city=&state=Select&urbanCode=&postalCode=94501&zip=
<https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=2&companyName=&address1=&address2=&city=&state=Select&urbanCode=&postalCode=94501&zip=>

**Comment by sjlu** [comment]
Gotcha.

Let me create a script that auto updates these locations from the postal service.

**Comment by willSonic** [comment]
Cool, 
Thank YOu...

**Comment by sjlu** [comment]
Hey @willSonic, I've made that script and am running it. I'll make a next bump with the name changes
